Update .gitpod.yml

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -1,12 +1,12 @@
 tasks:
-- name: Environment check
-  before: |
-    echo "Checking if required environment variables are set ..."
+    - name: Environment check
+    - before: |
+        echo "Checking if required environment variables are set ..."
 
-    if [[ -z ${RefArch_ADYEN_API_KEY+x} ]] || [[ -z ${RefArch_ADYEN_MERCHANT_ACCOUNT+x} ]] || [[ -z ${RefArch_ADYEN_CLIENT_KEY+x} ]] || [[ -z ${COMMERCE_API_CLIENT_ID+x} ]] || [[ -z ${COMMERCE_API_ORG_ID+x} ]] || [[ -z ${COMMERCE_API_SHORT_CODE+x} ]] || [[ -z ${COMMERCE_API_SITE_ID+x} ]] || [[ -z ${COMMERCE_API_DEFAULT_SITE+x} ]] || [[ -z ${SCAPI_URL+x} ]] || [[ -z ${OCAPI_URL+x} ]] || [[ -z ${ENVIRONMENT_ID+x} ]] || [[ -z ${PROJECT_ID+x} ]]; then
-      echo "Expected environment variables not found. Please set all required environment variables in your Gitpod environment and rerun session https://gitpod.io/variables. Check the project README for details."
-      exit 1
-    fi
+        if [[ -z ${RefArch_ADYEN_API_KEY+x} ]] || [[ -z ${RefArch_ADYEN_MERCHANT_ACCOUNT+x} ]] || [[ -z ${RefArch_ADYEN_CLIENT_KEY+x} ]] || [[ -z ${COMMERCE_API_CLIENT_ID+x} ]] || [[ -z ${COMMERCE_API_ORG_ID+x} ]] || [[ -z ${COMMERCE_API_SHORT_CODE+x} ]] || [[ -z ${COMMERCE_API_SITE_ID+x} ]] || [[ -z ${COMMERCE_API_DEFAULT_SITE+x} ]] || [[ -z ${SCAPI_URL+x} ]] || [[ -z ${OCAPI_URL+x} ]] || [[ -z ${ENVIRONMENT_ID+x} ]] || [[ -z ${PROJECT_ID+x} ]]; then
+          echo "Expected environment variables not found. Please set all required environment variables in your Gitpod environment and rerun session https://gitpod.io/variables. Check the project README for details."
+          exit 1
+        fi
 
 
 - name: Main Command  
